defaults:
  - _self_
  - agent: gcbc
  - suite: particle
  - override hydra/launcher: submitit_local

# Root Dir
root_dir: /Users/ozyurtf/Documents/ms-cs/spring-2025/deep-decision-making/assignments/assignment-1

# misc
seed: 42
device: cpu
save_video: true
use_tb: true
batch_size: 256

# experiment
obs_type: 'features' # pixels, features
experiment: gcbc
dataset_type: 'fixed_goal' # fixed_goal, changing_goal, multimodal

# expert dataset
train_test_ratio: 0.8
expert_dataset: ${root_dir}/data/${dataset_type}_1000demos.pkl

hydra:
  run:
    dir: ./exp_local/${experiment}/
